# name: Cypress Tests

# on:
#   push:
#   pull_request:
#     branches:
#       - main

# jobs:
#   cypress-run:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3
#       # Install NPM dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Setup Node.js
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18"
#           cache: "yarn"
#         env:
#           NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
#       - name: Cypress run
#         uses: cypress-io/github-action@v5.1.0 # use the explicit version number
#         with:
#           start: yarn start
#           command: yarn cypress:run
