export enum ChatActionTypes {
  CREATE_THREAD = "CREATE_THREAD",
  DELETE_THREAD = "DELETE_THREAD",
  SUBSCRIBE_USERS_TO_THREAD = "SUBSCRIBE_USERS_TO_THREAD",
  UPDATE_THREAD = "UPDATE_THREAD",
  CREATE_MESSAGE = "CREATE_MESSAGE",
  UPDATE_MESSAGE = "UPDATE_MESSAGE",
  DELETE_MESSAGE = "DELETE_MESSAGE",
  UPDATE_IS_TYPING = "UPDATE_IS_TYPING"
}
