export enum ChatActionTypes {
  CREATE_THREAD = "CREATE_THREAD",
  DELETE_THREAD = "DELETE_THREAD",
  SUBSCRIBE_USERS_TO_THREAD = "SUBSCRIBE_USERS_TO_THREAD",
  ADD_MESSAGE = "ADD_MESSAGE",
  EDIT_MESSAGE = "EDIT_MESSAGE",
  UPDATE_IS_TYPING = "UPDATE_IS_TYPING"
}
