name: "Publish Parsimony to Production"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  call-publish-libs:
    uses: jmilanes/parsimony/.github/workflows/publishLibs.yml@main
  call-deploy-API-service:
    needs: call-publish-libs
    uses: jmilanes/parsimony/.github/workflows/buildProductionParsimonyAPI.yml@main
  call-deploy-web-service:
    needs: call-publish-libs
    uses: jmilanes/parsimony/.github/workflows/buildProductionParsimonyWeb.yml@main
