name: "Publish Parsimony to Production"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency:
  group: ci-publish-parsimony-production-${{ github.ref }}-1
  cancel-in-progress: true
jobs:
  call-publish-libs:
    uses: ./.github/workflows/publishLibs.yml@main
  call-deploy-API-service:
    uses: ./.github/workflows/buildProductionParsimonyAPI.yml@main
  call-deploy-web-service:
    uses: ./.github/workflows/buildProductionParsimonyWeb.yml@main
