name: "Publish Parsimony to Production"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  # Tests, lint, publish broadcast
  publish-libs:
    uses: jmilanes/parsimony/.github/workflows/publishLibs.yml@main
  deploy-API-service:
    needs: publish-libs
    uses: jmilanes/parsimony/.github/workflows/buildProductionParsimonyAPI.yml@main
  deploy-web-service:
    needs: publish-libs
    uses: jmilanes/parsimony/.github/workflows/buildProductionParsimonyWeb.yml@main
